### ISSUE TITLE
[HW2] Difference fuzzer grader and git repository

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#202]
Hello!

When I try to grade my code for homework 2 I always get error on the first test case for the fuzzer. For example grade attempt with id 475.

However, when I use the fuzzer to test my code locally, I do not get any errors. I wonder if there could be some difference as to how the fuzzer is used when I run it locally and how it is run using the grader.

I run using this command:
`python3 tests/fuzz.py --i -n30`

Br
Jesper Amilon

**Comment by jeehoonkang** [comment]
I believe your fuzzer should not be different from gg's.  The gg grader is downloading `kecc-public` from: https://github.com/kaist-cp/kecc-public  And use the fuzzer there.

Did you merge the upstream changes in kecc-public?  If you already did, what's the output of gg?

**Comment by christofides** [comment]
Yes, I also did a fresh new git clone from kecc-public to make sure the issue is not with any failure to merge new changes. 

This is the output of gg (after passing the initial static tests):
```
    Finished release [optimized] target(s) in 0.05s
Building KECC..
Fuzzing with 30 test cases.
Test case #0 (skipped: 0)
Traceback (most recent call last):
  File "tests/fuzz.py", line 278, in <module>
    fuzz(tests_dir, fuzz_arg, args.num)
  File "tests/fuzz.py", line 236, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `cargo run --release --bin fuzz -- -i /app/files/checks/09ff3499-477e-45aa-95e4-15fa5a64e40f/checker/kecc-public/tests/test_polished.c` failed with exit code 101.
```

**Comment by jeehoonkang** [comment]
Did you run your fuzzer on the `cs420` machine, or another Ubuntu 20.04?  OS version may affect the test/fuzz results, so please make sure you're working in the same environment as the dev server and gg.
