### ISSUE TITLE
[HW3] panic in src/ir/equiv.rs when testing

### ISSUE THREAD

**Issue by ehfkzla** [kaist-cp/cs420#264]
안녕하세요, HW3에서 `examples/ir0`를 `examples/ir1`로 제대로 바꾸는지 테스팅을 하는 과정에서 알 수 없는 에러가 뜹니다.

`thread 'test_examples_simplify_cfg' panicked at 'called `Option::unwrap()` on a `None` value', src/ir/equiv.rs:78:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

`RUST_BACKTRACE1=1`을 하게 되면 아래와 같이 나타납니다.
```
➜  kecc git:(master) ✗ RUST_BACKTRACE=1 RUST_MIN_STACK=33554432 cargo test test_examples_simplify_cfg  # run simplify_cfg test
    Finished test [unoptimized + debuginfo] target(s) in 0.12s
     Running target/debug/deps/kecc-569514590f91d646

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/fuzz-b22fd85d07c8dde5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/kecc-745b3e5d32df4a3c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_examples-0f404fad24ae210a

running 1 test
test test_examples_simplify_cfg ... FAILED

failures:

---- test_examples_simplify_cfg stdout ----
thread 'test_examples_simplify_cfg' panicked at 'called `Option::unwrap()` on a `None` value', src/ir/equiv.rs:77:31
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/io/mod.rs:1504
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::panicking::panic
             at src/libcore/panicking.rs:54
  15: core::option::Option<T>::unwrap
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/macros/mod.rs:34
  16: kecc::ir::equiv::traverse_preorder
             at src/ir/equiv.rs:77
  17: kecc::ir::equiv::<impl kecc::utils::IsEquiv for kecc::ir::FunctionDefinition>::is_equiv
             at src/ir/equiv.rs:345
  18: <core::option::Option<T> as kecc::utils::IsEquiv>::is_equiv
             at src/utils.rs:82
  19: kecc::ir::equiv::<impl kecc::utils::IsEquiv for kecc::ir::Declaration>::is_equiv
             at src/ir/equiv.rs:63
  20: kecc::ir::equiv::<impl kecc::utils::IsEquiv for kecc::ir::TranslationUnit>::is_equiv
             at src/ir/equiv.rs:20
  21: kecc::tests::test_opt
             at ./src/tests.rs:195
  22: test_examples::test_examples_simplify_cfg
             at tests/test_examples.rs:127
  23: test_examples::test_examples_simplify_cfg::{{closure}}
             at tests/test_examples.rs:114
  24: core::ops::function::FnOnce::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
  25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  26: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  27: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  28: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  29: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  30: test::run_test_in_process
             at src/libtest/lib.rs:541
  31: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_examples_simplify_cfg

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out

error: test failed, to rerun pass '--test test_examples'
```

이를 어떻게 해결하면 좋을까요?

**Comment by kimjungwow** [comment]
I hope checking whether you try to access the value which is not in the structure such as BTreeMap can help you.  
For example, you may access (using `get_mut()`, `get()`, etc) the value after removing that value from BTreeMap.

**Comment by ehfkzla** [comment]
Hmm, actually i already checked that. But I don't use get or get_mut on BTreeMap..

**Comment by LockOne** [comment]
I guess some of the blocks in your generated IR are jumping to blocks that do not exist in the generated IR. 
It crashes on `src/ir/equiv.rs:77` which generates traverse order of given IR tree,
and it seems the bids got from block jumps do not exist in the block tree.

**Comment by cmpark0126** [comment]
Is it resolved?

**Comment by ehfkzla** [comment]
@cmpark0126  actually no. By the way, does homework3 have dependency with homework2?

**Comment by cmpark0126** [comment]
@ehfkzla No, there is no dependency between homework 3 and homework 2.

**Comment by ehfkzla** [comment]
@cmpark0126 
1. all passed except `examples/ir0` and `examples/ir1`
2. implemented referring recorded video.
3. didn't use `unsafe`

then I don't know why this error is occurred...

**Comment by cmpark0126** [comment]
As I know this issue is resolved.

If you have further questions, please reopen it.
