### ISSUE TITLE
[HW2] Problem with Fuzzer

### ISSUE THREAD

**Issue by Gabriel4256** [kaist-cp/cs420#267]
Hi, I have difficulty using fuzzer.
When I try to use it, error message as below appears.
```
python3 tests/fuzz.py -i
Building KECC..
    Finished release [optimized] target(s) in 0.02s
Fuzzing with infinitely many test cases.  Please press [ctrl+C] to break.
Test case #0 (skipped: 0)
Traceback (most recent call last):
  File "tests/fuzz.py", line 278, in <module>
    fuzz(tests_dir, fuzz_arg, args.num)
  File "tests/fuzz.py", line 236, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `cargo run --release --bin fuzz -- -i /home/gabriel/바탕화면/kecc-public/tests/test_polished.c` failed with exit code 101.

```

And when I try reducing, error as below occurs.
```
python3 tests/fuzz.py -i --reduce
Building KECC..
    Finished release [optimized] target(s) in 0.02s

C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/gabriel/바탕화면/kecc-public/tests/test_reduced.c $DIR
  cd $DIR
  /home/gabriel/바탕화면/kecc-public/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.

```

But, there's no problem when just running `test_polished.c`
```
cargo run -- tests/test_polished.c --irrun
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/kecc tests/test_polished.c --irrun`
[result] 157

```

Executed on
* Python 3..6.8
* Linux Mint 19.3 MATE
* rustc 1.44.1

It seems like panic occurs somewhere, but I cannot know what caused it. 
Please let me know if I am missing something.
Thank you.`

**Comment by cmpark0126** [comment]
Please try to use `cargo run --bin fuzz tests/test_polished.c -i`

**Comment by Ngiong** [comment]
Hi,
May I ask what's the difference between these two?
```
python3 tests/fuzz.py --irgen
cargo run --bin fuzz tests/test_polished.c -i
```

**Comment by Gabriel4256** [comment]
This is the result of `cargo run --bin fuzz tests/test_polished.c -i`

```
cargo run --bin fuzz tests/test_polished.c -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/fuzz tests/test_polished.c -i`
gcc: 72, kecc: 241
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `72`,
 right: `241`', src/tests.rs:119:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

It looks like the return value from my ir is wrong, but `test_polished.c` is too large to deal with.
Is there any other way to reduce the file?

**Comment by cmpark0126** [comment]
@Gabriel4256 

Please try to use `python3 tests/fuzz.py --print --reduce`. 

Here is a document for this command: https://github.com/kaist-cp/kecc-public#fuzzing.

**Comment by Gabriel4256** [comment]
@cmpark0126 

Unfortunately, when I use `python3 tests/fuzz.py --print --reduce`, same error occurs.
```
python3 tests/fuzz.py --print --reduce
Building KECC..
    Finished release [optimized] target(s) in 0.14s

C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/gabriel/바탕화면/original/tests/test_reduced.c $DIR
  cd $DIR
  /home/gabriel/바탕화면/original/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.

```

**Comment by cmpark0126** [comment]
@Ngiong 

First, `cargo run --bin fuzz tests/test_polished.c -i` tests whether `kecc ir` from given example code returns the same value as `gcc`.

Second, `python3 tests/fuzz.py --irgen` uses the above command with random c example created by `csmith`. Please refer to this link: https://github.com/kaist-cp/kecc-public#run-1

**Comment by cmpark0126** [comment]
@Gabriel4256 
I'm sorry... Please try to use `python3 tests/fuzz.py -i - r`...

**Comment by Gabriel4256** [comment]
same error occurs again.

```
python3 tests/fuzz.py -i -r
Building KECC..
    Finished release [optimized] target(s) in 0.03s

C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/gabriel/바탕화면/original/tests/test_reduced.c $DIR
  cd $DIR
  /home/gabriel/바탕화면/original/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.

```

By the way, I thought `python3 tests/fuzz.py --print --reduce` is just for HW1, can it also be used for HW2?

**Comment by cmpark0126** [comment]
@Gabriel4256 
> By the way, I thought python3 tests/fuzz.py --print --reduce is just for HW1, can it also be used for HW2?

Please refer to the link I attached above: https://github.com/kaist-cp/kecc-public#reduce

I need the sequence output to solve this issue actually...

It may be a hassle, but please do it one more time.

Please try to use the commands below in order and share the error messages of them: 

1. `python3 tests/fuzz.py -i`
2. `cargo run --bin fuzz tests/test_polished.c -i` 
3. `python3 tests/fuzz.py -i -r`
4. `cargo run --bin fuzz tests/test_reduced.c -i` 

Additionally, pleas share your `tests/reduce-criteria-template.sh` also.

**Comment by Gabriel4256** [comment]
@cmpark0126 

Sorry for bothering you badly and thanks for all of your efforts.

`python3 tests/fuzz.py -i`
```
python3 tests/fuzz.py -i
Building KECC..
    Finished release [optimized] target(s) in 0.04s
Fuzzing with infinitely many test cases.  Please press [ctrl+C] to break.
Test case #0 (skipped: 0)
Test case #1 (skipped: 0)
Traceback (most recent call last):
  File "tests/fuzz.py", line 278, in <module>
    fuzz(tests_dir, fuzz_arg, args.num)
  File "tests/fuzz.py", line 236, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `cargo run --release --bin fuzz -- -i /home/gabriel/바탕화면/original/tests/test_polished.c` failed with exit code 101.
```

`cargo run --bin fuzz tests/test_polished.c -i`

```
cargo run --bin fuzz tests/test_polished.c -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/fuzz tests/test_polished.c -i`
gcc: 0, kecc: 93
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `93`', src/tests.rs:119:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

`python3 tests/fuzz.py -i -r`

```
python3 tests/fuzz.py -i -r
Building KECC..
    Finished release [optimized] target(s) in 0.03s

C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/gabriel/바탕화면/original/tests/test_reduced.c $DIR
  cd $DIR
  /home/gabriel/바탕화면/original/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
```

`cargo run --bin fuzz tests/test_reduced.c -i`

```
cargo run --bin fuzz tests/test_reduced.c -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/fuzz tests/test_reduced.c -i`
gcc: 0, kecc: 93
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `93`', src/tests.rs:119:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Finally, this is the content of my `tests/reduce-criteria-template.sh`.

```
#!/usr/bin/env bash

rm -f out*.txt

#ulimit -t 3000                                                                                                                                                                                             
#ulimit -v 2000000                                                                                                                                                                                          

if
  [ $FUZZ_ARG = '-i' ] &&\
  (! clang -pedantic -Wall -Werror=strict-prototypes -O1 -c test_reduced.c  > out.txt 2>&1 ||\
  grep 'main-return-type' out.txt ||\
  grep 'conversions than data arguments' out.txt ||\
  grep 'int-conversion' out.txt ||\
  grep 'incompatible redeclaration' out.txt ||\
  grep 'ordered comparison between pointer and zero' out.txt ||\
  grep 'ordered comparison between pointer and integer' out.txt ||\
  grep 'eliding middle term' out.txt ||\
  grep 'end of non-void function' out.txt ||\
  grep 'invalid in C99' out.txt ||\
  grep 'specifies type' out.txt ||\
  grep 'should return a value' out.txt ||\
  grep 'uninitialized' out.txt ||\
  grep 'incompatible pointer to' out.txt ||\
  grep 'incompatible integer to' out.txt ||\
  grep 'type specifier missing' out.txt ||\
  grep 'implicit-function-declaration' out.txt ||\
  grep 'infinite-recursion' out.txt ||\
  grep 'pointer-bool-conversion' out.txt ||\
  grep 'non-void function does not return a value' out.txt ||\
  grep 'too many arguments in call' out.txt ||\
  grep 'declaration does not declare anything' out.txt ||\
  grep 'not equal to a null pointer is always true' out.txt ||\
  grep 'empty struct is a GNU extension' out.txt ||\
  ! gcc -Wall -Wextra -O2 test_reduced.c > outa.txt 2>&1 ||\
  grep 'uninitialized' outa.txt ||\
  grep 'without a cast' outa.txt ||\
  grep 'control reaches end' outa.txt ||\
  grep 'return type defaults' outa.txt ||\
  grep 'cast from pointer to integer' outa.txt ||\
  grep 'useless type name in empty declaration' outa.txt ||\
  grep 'no semicolon at end' outa.txt ||\
  grep 'type defaults to' outa.txt ||\
  grep 'too few arguments for format' outa.txt ||\
  grep 'incompatible pointer' outa.txt ||\
  grep 'ordered comparison of pointer with integer' outa.txt ||\
  grep 'declaration does not declare anything' outa.txt ||\
  grep 'expects type' outa.txt ||\
  grep 'pointer from integer' outa.txt ||\
  grep 'incompatible implicit' outa.txt ||\
  grep 'excess elements in struct initializer' outa.txt ||\
  grep 'comparison between pointer and integer' outa.txt ||\
  ! gcc -O1 test_reduced.c > cc_out1.txt 2>&1 ||\
  ! gcc -O2 test_reduced.c > cc_out2.txt 2>&1 ||\
  ! cargo run --manifest-path $PROJECT_DIR/Cargo.toml --release -- --parse test_reduced.c >/dev/null 2>&1)
then
  exit 1
fi

cargo run --manifest-path $PROJECT_DIR/Cargo.toml --release --bin fuzz -- $FUZZ_ARG test_reduced.c 2>&1 | grep -q '(left == right)'
```

**Comment by cmpark0126** [comment]
Ah... Could you check if `clang` is installed?

**Comment by Gabriel4256** [comment]
@cmpark0126 

Oops.... It's not installed, so I installed it and  re-tried same command sequences again.
The results were same except for `python3 tests/fuzz.py -i -r`.

For the case of `python3 tests/fuzz.py -i -r`, now it runs for a very long time, it seems like endless.
```
python3 tests/fuzz.py -i -r
Building KECC..
    Finished release [optimized] target(s) in 0.10s
```
Is this normal thing?

**Comment by cmpark0126** [comment]
Generally, it takes some time to reduce C example.

Great! If you further questions here, feel free to reopen this issue :)
