### ISSUE TITLE
[HW2] Is there any other solution to this bug of creduce?

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs420#308]
Due to problems (1) and (2) below, I am very confused now, and I am thinking about whether to skip this problems and start doing Homework 3.

However, I don't know if I can think that I finished my homework 2 with this. 
So ***I am wondering if there are other solutions for these Fuzzer error.*** Can I get some advice?

FYI, My ubuntu version is `Ubuntu 20.04.1 LTS` and I already installed `clang`.

 (1) says that replace `tests/reduce-criteria-template.sh` with the previous version for running Fuzzer
 (2) says that update `tests/reduce-criteria-template.sh` to latest version for removing unintended test

Below are more specific explanation for (1) and (2) 
## (1) Error with latest reduce-template (at 2020.10.13)
When I use command `python3 tests/fuzz.py -i -r`, Error occurs like below.

```
C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/seungminjeon/Desktop/study/kaist-cp-cs420/tests/test_reduced.c $DIR
  cd $DIR
  /home/seungminjeon/Desktop/study/kaist-cp-cs420/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
```

So, following TA's suggestion on https://github.com/kaist-cp/cs420/issues/170#issuecomment-637482746, I replaced `tests/reduce-criteria-template.sh` with the previous version and tried to fix this problem like (2).

## (2) Error with the previous reduce-template
Refer to https://github.com/kaist-cp/cs420/issues/170#issuecomment-637482746, I used the previous version of `tests/reduce-criteria-template.sh`. 

Its reduce(`python3 tests/fuzz.py -i -r`) works fine. 
But some reduced results in `test_reduced.c` are still a problem for my homework 2. The codes below are examples.

```c
// case 1 : uninitialized value `b`
void a() { unsigned b = b; }
int main() {}
```

```c
// case 2 : return type of `main()`
void main() {}
```

- case 1 
 I saw the same issue at https://github.com/kaist-cp/cs420/issues/218.
 Following instructor's answer, I try to ignore this problem. 

- case 2
 This case has also been issued before at https://github.com/kaist-cp/cs420/issues/123.
 But, the answer is to update `tests/reduce-criteria.sh` to latest version. It forced me to go back ***(1) Error with latest reduce-template***

**Comment by zzz845zz** [comment]
> Due to problems (1) and (2) below, I am very confused now, and I am thinking about whether to skip this problems and start doing Homework 3.
> 
> However, I don't know if I can think that I finished my homework 2 with this.
> So _**I am wondering if there are other solutions for these Fuzzer error.**_ Can I get some advice?
> 
> FYI, My ubuntu version is `Ubuntu 20.04.1 LTS` and I already installed `clang`.
> 
> (1) says that replace `tests/reduce-criteria-template.sh` with the previous version for running Fuzzer
> (2) says that update `tests/reduce-criteria-template.sh` to latest version for removing unintended test
> 
> Below are more specific explanation for (1) and (2)
> 
> ## (1) Error with latest KECC (at 2020.10.13)
> When I use command `python3 tests/fuzz.py -i -r`, Error occurs like below.
> 
> ```
> C-Reduce cannot run because the interestingness test does not return
> zero. Please ensure that it does so not only in the directory where
> you are invoking C-Reduce, but also in an arbitrary temporary
> directory containing only the files that are being reduced. In other
> words, running these commands:
> 
>   DIR=`mktemp -d`
>   cp /home/seungminjeon/Desktop/study/kaist-cp-cs420/tests/test_reduced.c $DIR
>   cd $DIR
>   /home/seungminjeon/Desktop/study/kaist-cp-cs420/tests/reduce-criteria.sh
>   echo $?
> 
> should result in "0" being echoed to the terminal.
> 
> See "creduce --help" for more information.
> 
> 
> Traceback (most recent call last):
>   File "tests/fuzz.py", line 276, in <module>
>     creduce(tests_dir, fuzz_arg)
>   File "tests/fuzz.py", line 198, in creduce
>     raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
> Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
> ```
> 
> So, following TA's suggestion on [#170 (comment)](https://github.com/kaist-cp/cs420/issues/170#issuecomment-637482746), I replaced `tests/reduce-criteria-template.sh` with the previous version and tried to fix this problem like (2).
> 
> ## (2) Error with the previous version of reduce-template
> Refer to [#170 (comment)](https://github.com/kaist-cp/cs420/issues/170#issuecomment-637482746), I used the previous version of `tests/reduce-criteria-template.sh`.
> 
> Its reduce(`python3 tests/fuzz.py -i -r`) works fine.
> But some reduced results in `test_reduced.c` are still a problem for my homework 2. The codes below are examples.
> 
> ```c
> // case 1 : uninitialized value `b`
> void a() { unsigned b = b; }
> int main() {}
> ```
> 
> ```c
> // case 2 : return type of `main()`
> void main() {}
> ```
> 
> * case 1
>   I saw the same issue at #218.
>   Following instructor's answer, I try to ignore this problem.
> * case 2
>   This case has also been issued before at #123.
>   But, the answer is to update `tests/reduce-criteria.sh` to latest version. It forced me to go back _**(1) Error with latest KECC**_

**Comment by zzz845zz** [comment]
In the latest KECC, `python3 tests / fuzz.py -i -r` error occurred due to my irgen implementation errors related to `width`, `is_signed`.

When I manually found and fixed that error, **creduce** worked well.
