### ISSUE TITLE
[Question] Homework submission csmith build error

### ISSUE THREAD

**Issue by p51lee** [kaist-cp/cs420#331]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--
I have submitted hw1 to gg.kaist.ac.kr, but it seems that there are csmith build errors. It worked fine when I tested the code myself, is there something wrong with my code?
```
===== SETUP =====

===== CHECK =====
[2022-03-04 16:06:33,374: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.59.0 (9d1b2106e 2022-02-23)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source $HOME/.cargo/env
Cloning into 'kecc-public'...
   Compiling libc v0.2.112
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
    Checking cfg-if v1.0.0
   Compiling syn v1.0.86
   Compiling autocfg v1.0.1
    Checking ppv-lite86 v0.2.16
   Compiling peg-runtime v0.8.0
    Checking fastrand v1.6.0
    Checking either v1.6.1
    Checking remove_dir_all v0.5.3
    Checking hexf-parse v0.2.1
    Checking lang-c v0.11.0
    Checking itertools v0.10.3
   Compiling num-traits v0.2.14
   Compiling quote v1.0.14
    Checking getrandom v0.2.4
    Checking wait-timeout v0.2.0
    Checking tempfile v3.3.0
    Checking rand_core v0.6.3
   Compiling peg-macros v0.8.0
    Checking rand_chacha v0.3.1
    Checking rand v0.8.4
    Checking ordered-float v2.10.0
    Checking peg v0.8.0
   Compiling thiserror-impl v1.0.30
    Checking thiserror v1.0.30
    Checking kecc v0.1.0 (/app/files/checks/1cedd5a2-d358-4515-868c-bc33cba731b0/kecc-public)
    Finished dev [unoptimized + debuginfo] target(s) in 9.92s
   Compiling proc-macro2 v1.0.36
   Compiling libc v0.2.112
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling syn v1.0.86
   Compiling ppv-lite86 v0.2.16
   Compiling peg-runtime v0.8.0
   Compiling remove_dir_all v0.5.3
   Compiling either v1.6.1
   Compiling fastrand v1.6.0
   Compiling hexf-parse v0.2.1
   Compiling lang-c v0.11.0
   Compiling itertools v0.10.3
   Compiling num-traits v0.2.14
   Compiling quote v1.0.14
   Compiling getrandom v0.2.4
   Compiling tempfile v3.3.0
   Compiling wait-timeout v0.2.0
   Compiling peg-macros v0.8.0
   Compiling rand_core v0.6.3
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.4
   Compiling ordered-float v2.10.0
   Compiling peg v0.8.0
   Compiling thiserror-impl v1.0.30
   Compiling thiserror v1.0.30
   Compiling kecc v0.1.0 (/app/files/checks/1cedd5a2-d358-4515-868c-bc33cba731b0/kecc-public)
    Finished release [optimized] target(s) in 19.31s
     Running unittests (target/release/deps/kecc-19bdc2ab6a7458d2)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test_examples.rs (target/release/deps/test_examples-dd2b560e79caef77)

running 1 test
test test_examples_write_c ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 10 filtered out; finished in 1.29s

    Finished release [optimized] target(s) in 0.03s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 43  622k   43  272k    0     0   159k      0  0:00:03  0:00:01  0:00:02  159k
100  622k  100  622k    0     0   263k      0  0:00:02  0:00:02 --:--:--  263k
csmith-2.3.0/
csmith-2.3.0/configure.ac
csmith-2.3.0/scripts/
csmith-2.3.0/scripts/launchn.pl
csmith-2.3.0/scripts/compiler_test.pl
csmith-2.3.0/scripts/Makefile.in
csmith-2.3.0/scripts/CMakeLists.txt
csmith-2.3.0/scripts/compiler_test.in
csmith-2.3.0/scripts/Makefile.am
csmith-2.3.0/runtime/
csmith-2.3.0/runtime/windows/
csmith-2.3.0/runtime/windows/stdint.h
csmith-2.3.0/runtime/safe_abbrev.h
csmith-2.3.0/runtime/stdint_ia64.h
csmith-2.3.0/runtime/platform_generic.h
csmith-2.3.0/runtime/platform_avr.h
csmith-2.3.0/runtime/safe_math_macros_notmp.m4
csmith-2.3.0/runtime/random_inc.h
csmith-2.3.0/runtime/safe_math.m4
csmith-2.3.0/runtime/stdint_msp430.h
csmith-2.3.0/runtime/platform_msp430.h
csmith-2.3.0/runtime/custom_stdint_x86.h
csmith-2.3.0/runtime/csmith.h
csmith-2.3.0/runtime/stdint_ia32.h
csmith-2.3.0/runtime/Makefile.in
csmith-2.3.0/runtime/custom_limits.h
csmith-2.3.0/runtime/CMakeLists.txt
csmith-2.3.0/runtime/safe_math_macros.m4
csmith-2.3.0/runtime/stdint_avr.h
csmith-2.3.0/runtime/volatile_runtime.c
csmith-2.3.0/runtime/volatile_runtime.h
csmith-2.3.0/runtime/csmith_minimal.h
csmith-2.3.0/runtime/Makefile.am
csmith-2.3.0/aclocal.m4
csmith-2.3.0/m4/
csmith-2.3.0/m4/ltoptions.m4
csmith-2.3.0/m4/ltsugar.m4
csmith-2.3.0/m4/libtool.m4
csmith-2.3.0/m4/lt~obsolete.m4
csmith-2.3.0/m4/ltversion.m4
csmith-2.3.0/AUTHORS
csmith-2.3.0/TODO
csmith-2.3.0/version.m4
csmith-2.3.0/autoconf/
csmith-2.3.0/autoconf/install-sh
csmith-2.3.0/autoconf/config.guess
csmith-2.3.0/autoconf/ltmain.sh
csmith-2.3.0/autoconf/config.sub
csmith-2.3.0/autoconf/missing
csmith-2.3.0/autoconf/compile
csmith-2.3.0/autoconf/depcomp
csmith-2.3.0/COPYING
csmith-2.3.0/NEWS
csmith-2.3.0/doc/
csmith-2.3.0/doc/probabilities.txt
csmith-2.3.0/doc/Makefile.in
csmith-2.3.0/doc/CMakeLists.txt
csmith-2.3.0/doc/Makefile.am
csmith-2.3.0/configure
csmith-2.3.0/ChangeLog
csmith-2.3.0/git-hash.sh
csmith-2.3.0/INSTALL
csmith-2.3.0/README
csmith-2.3.0/cmake/
csmith-2.3.0/cmake/GetGitRevisionDescription.cmake.in
csmith-2.3.0/cmake/GetGitRevisionDescription.cmake
csmith-2.3.0/cmake_config.h.in
csmith-2.3.0/Makefile.in
csmith-2.3.0/config.h.in
csmith-2.3.0/CMakeLists.txt
csmith-2.3.0/src/
csmith-2.3.0/src/DefaultOutputMgr.cpp
csmith-2.3.0/src/Error.cpp
csmith-2.3.0/src/StringUtils.cpp
csmith-2.3.0/src/FunctionInvocationBinary.cpp
csmith-2.3.0/src/DeltaMonitor.h
csmith-2.3.0/src/StatementReturn.h
csmith-2.3.0/src/DepthSpec.cpp
csmith-2.3.0/src/Sequence.h
csmith-2.3.0/src/SafeOpFlags.h
csmith-2.3.0/src/Probabilities.h
csmith-2.3.0/src/ExtensionValue.h
csmith-2.3.0/src/SequenceLineParser.h
csmith-2.3.0/src/CrestExtension.h
csmith-2.3.0/src/DFSOutputMgr.h
csmith-2.3.0/src/Function.cpp
csmith-2.3.0/src/CFGEdge.h
csmith-2.3.0/src/ReducerOutputMgr.cpp
csmith-2.3.0/src/Function.h
csmith-2.3.0/src/StatementFor.h
csmith-2.3.0/src/StatementIf.cpp
csmith-2.3.0/src/Reducer.h
csmith-2.3.0/src/SimpleDeltaRndNumGenerator.cpp
csmith-2.3.0/src/SplatExtension.cpp
csmith-2.3.0/src/SequenceFactory.h
csmith-2.3.0/src/Type.cpp
csmith-2.3.0/src/Statement.cpp
csmith-2.3.0/src/Bookkeeper.cpp
csmith-2.3.0/src/CoverageTestExtension.h
csmith-2.3.0/src/rand48/
csmith-2.3.0/src/rand48/rand48.h
csmith-2.3.0/src/rand48/lrand48.c
csmith-2.3.0/src/rand48/_rand48.c
csmith-2.3.0/src/rand48/srand48.c
csmith-2.3.0/src/AbsProgramGenerator.h
csmith-2.3.0/src/platform.cpp
csmith-2.3.0/src/DepthSpec.h
csmith-2.3.0/src/OutputMgr.h
csmith-2.3.0/src/FunctionInvocationUser.cpp
csmith-2.3.0/src/DFSOutputMgr.cpp
csmith-2.3.0/src/AbsRndNumGenerator.cpp
csmith-2.3.0/src/Expression.cpp
csmith-2.3.0/src/DFSRndNumGenerator.h
csmith-2.3.0/src/CompatibleChecker.h
csmith-2.3.0/src/DFSProgramGenerator.cpp
csmith-2.3.0/src/KleeExtension.h
csmith-2.3.0/src/DFSRndNumGenerator.cpp
csmith-2.3.0/src/FactMgr.h
csmith-2.3.0/src/ReducerOutputMgr.h
csmith-2.3.0/src/Expression.h
csmith-2.3.0/src/CommonMacros.h
csmith-2.3.0/src/ExpressionComma.h
csmith-2.3.0/src/FunctionInvocationUnary.h
csmith-2.3.0/src/VectorFilter.cpp
csmith-2.3.0/src/AbsProgramGenerator.cpp
csmith-2.3.0/src/ExpressionVariable.h
csmith-2.3.0/src/Probabilities.cpp
csmith-2.3.0/src/FunctionInvocationUser.h
csmith-2.3.0/src/Error.h
csmith-2.3.0/src/Variable.h
csmith-2.3.0/src/ExpressionVariable.cpp
csmith-2.3.0/src/Finalization.h
csmith-2.3.0/src/SimpleDeltaSequence.cpp
csmith-2.3.0/src/LinearSequence.h
csmith-2.3.0/src/MspFilters.cpp
csmith-2.3.0/src/ExpressionComma.cpp
csmith-2.3.0/src/VariableSelector.cpp
csmith-2.3.0/src/ExtensionMgr.cpp
csmith-2.3.0/src/FactUnion.cpp
csmith-2.3.0/src/CFGEdge.cpp
csmith-2.3.0/src/PartialExpander.cpp
csmith-2.3.0/src/Effect.cpp
csmith-2.3.0/src/StatementIf.h
csmith-2.3.0/src/FactUnion.h
csmith-2.3.0/src/ArrayVariable.h
csmith-2.3.0/src/RandomProgramGenerator.cpp
csmith-2.3.0/src/Sequence.cpp
csmith-2.3.0/src/CVQualifiers.cpp
csmith-2.3.0/src/DefaultRndNumGenerator.cpp
csmith-2.3.0/src/CGOptions.cpp
csmith-2.3.0/src/ExpressionAssign.cpp
csmith-2.3.0/src/DefaultProgramGenerator.h
csmith-2.3.0/src/StatementAssign.cpp
csmith-2.3.0/src/KleeExtension.cpp
csmith-2.3.0/src/ExpressionFuncall.h
csmith-2.3.0/src/StatementExpr.cpp
csmith-2.3.0/src/util.h
csmith-2.3.0/src/random.cpp
csmith-2.3.0/src/FunctionInvocation.cpp
csmith-2.3.0/src/Bookkeeper.h
csmith-2.3.0/src/StatementReturn.cpp
csmith-2.3.0/src/Block.cpp
csmith-2.3.0/src/RandomNumber.cpp
csmith-2.3.0/src/Constant.h
csmith-2.3.0/src/DefaultProgramGenerator.cpp
csmith-2.3.0/src/Common.h
csmith-2.3.0/src/Constant.cpp
csmith-2.3.0/src/FunctionInvocationUnary.cpp
csmith-2.3.0/src/StatementAssign.h
csmith-2.3.0/src/MspFilters.h
csmith-2.3.0/src/Lhs.cpp
csmith-2.3.0/src/StatementContinue.h
csmith-2.3.0/src/Variable.cpp
csmith-2.3.0/src/FactPointTo.cpp
csmith-2.3.0/src/CGContext.h
csmith-2.3.0/src/StatementFor.cpp
csmith-2.3.0/src/FactPointTo.h
csmith-2.3.0/src/CGContext.cpp
csmith-2.3.0/src/Lhs.h
csmith-2.3.0/src/CoverageTestExtension.cpp
csmith-2.3.0/src/StatementGoto.h
csmith-2.3.0/src/StatementArrayOp.cpp
csmith-2.3.0/src/Fact.cpp
csmith-2.3.0/src/Filter.h
csmith-2.3.0/src/random.h
csmith-2.3.0/src/StatementBreak.h
csmith-2.3.0/src/git_version.cpp.in
csmith-2.3.0/src/StatementContinue.cpp
csmith-2.3.0/src/Reducer.cpp
csmith-2.3.0/src/VectorFilter.h
csmith-2.3.0/src/Statement.h
csmith-2.3.0/src/AbsExtension.h
csmith-2.3.0/src/StringUtils.h
csmith-2.3.0/src/Makefile.in
csmith-2.3.0/src/util.cpp
csmith-2.3.0/src/StatementArrayOp.h
csmith-2.3.0/src/StatementExpr.h
csmith-2.3.0/src/RandomNumber.h
csmith-2.3.0/src/Enumerator.h
csmith-2.3.0/src/platform.h
csmith-2.3.0/src/DFSProgramGenerator.h
csmith-2.3.0/src/Finalization.cpp
csmith-2.3.0/src/SplatExtension.h
csmith-2.3.0/src/Effect.h
csmith-2.3.0/src/CMakeLists.txt
csmith-2.3.0/src/FunctionInvocation.h
csmith-2.3.0/src/Filter.cpp
csmith-2.3.0/src/FactMgr.cpp
csmith-2.3.0/src/CrestExtension.cpp
csmith-2.3.0/src/ExtensionValue.cpp
csmith-2.3.0/src/Fact.h
csmith-2.3.0/src/DefaultOutputMgr.h
csmith-2.3.0/src/SafeOpFlags.cpp
csmith-2.3.0/src/PartialExpander.h
csmith-2.3.0/src/git_version.h
csmith-2.3.0/src/Block.h
csmith-2.3.0/src/DefaultRndNumGenerator.h
csmith-2.3.0/src/AbsExtension.cpp
csmith-2.3.0/src/ArrayVariable.cpp
csmith-2.3.0/src/ProbabilityTable.h
csmith-2.3.0/src/CompatibleChecker.cpp
csmith-2.3.0/src/SimpleDeltaSequence.h
csmith-2.3.0/src/ExpressionAssign.h
csmith-2.3.0/src/StatementGoto.cpp
csmith-2.3.0/src/VariableSelector.h
csmith-2.3.0/src/LinearSequence.cpp
csmith-2.3.0/src/OutputMgr.cpp
csmith-2.3.0/src/FunctionInvocationBinary.h
csmith-2.3.0/src/Type.h
csmith-2.3.0/src/DeltaMonitor.cpp
csmith-2.3.0/src/CVQualifiers.h
csmith-2.3.0/src/StatementBreak.cpp
csmith-2.3.0/src/AbsRndNumGenerator.h
csmith-2.3.0/src/ExpressionFuncall.cpp
csmith-2.3.0/src/SimpleDeltaRndNumGenerator.h
csmith-2.3.0/src/SequenceFactory.cpp
csmith-2.3.0/src/Makefile.am
csmith-2.3.0/src/ExtensionMgr.h
csmith-2.3.0/src/CGOptions.h
csmith-2.3.0/Makefile.am
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for libbsd
-- Check for libbsd: not found
-- Looking for bsd/stdlib.h
-- Looking for bsd/stdlib.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for lrand48
-- Looking for lrand48 - found
-- Looking for srand48_deterministic
-- Looking for srand48_deterministic - not found
-- Check for M4 macro processor
CMake Error at CMakeLists.txt:136 (message):
  The `m4' macro processor was not found.  You must install `m4' before you
  can to compile Csmith.


-- Configuring incomplete, errors occurred!
See also "/app/files/checks/1cedd5a2-d358-4515-868c-bc33cba731b0/kecc-public/tests/csmith-2.3.0/CMakeFiles/CMakeOutput.log".
See also "/app/files/checks/1cedd5a2-d358-4515-868c-bc33cba731b0/kecc-public/tests/csmith-2.3.0/CMakeFiles/CMakeError.log".
Building KECC..
Traceback (most recent call last):
  File "tests/fuzz.py", line 280, in <module>
    fuzz(tests_dir, fuzz_arg, args.num)
  File "tests/fuzz.py", line 208, in fuzz
    csmith_bin, csmith_inc = install_csmith(tests_dir)
  File "tests/fuzz.py", line 92, in install_csmith
    raise Exception("Failed to build Csmith (exit code: {})".format(proc.returncode))
Exception: Failed to build Csmith (exit code: 1)
```

**Comment by minseongg** [comment]
https://github.com/kaist-cp/cs420/issues/320#issuecomment-1059016367

**Comment by jeehoonkang** [comment]
Thanks for the report. It's now fixed.

**Comment by jeehoonkang** [comment]
@TanapTheTimid pinging to notify you
