### ISSUE TITLE
[Question] I have problem with connecting to the server

### ISSUE THREAD

**Issue by chhong39** [kaist-cp/cs420#332]
I was able to connect to the server yesterday but Today, I cannot connect to my server with the following error strings.

[21:02:56.423] Log Level: 2
[21:02:56.424] remote-ssh@0.76.1
[21:02:56.424] win32 x64
[21:02:56.432] SSH Resolver called for "ssh-remote+cs420", attempt 1
[21:02:56.432] "remote.SSH.useLocalServer": false
[21:02:56.432] "remote.SSH.showLoginTerminal": false
[21:02:56.432] "remote.SSH.remotePlatform": {"cs420":"linux"}
[21:02:56.433] "remote.SSH.path": undefined
[21:02:56.433] "remote.SSH.configFile": undefined
[21:02:56.433] "remote.SSH.useFlock": true
[21:02:56.433] "remote.SSH.lockfilesInTmp": false
[21:02:56.433] "remote.SSH.localServerDownload": auto
[21:02:56.433] "remote.SSH.remoteServerListenOnSocket": false
[21:02:56.433] "remote.SSH.showLoginTerminal": false
[21:02:56.433] "remote.SSH.defaultExtensions": []
[21:02:56.433] "remote.SSH.loglevel": 2
[21:02:56.433] "remote.SSH.enableDynamicForwarding": true
[21:02:56.434] "remote.SSH.enableRemoteCommand": false
[21:02:56.434] "remote.SSH.serverPickPortsFromRange": {}
[21:02:56.434] "remote.SSH.serverInstallPath": {}
[21:02:56.457] SSH Resolver called for host: cs420
[21:02:56.457] Setting up SSH remote "cs420"
[21:02:56.461] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[21:02:56.464] Install and start server if needed
[21:02:56.466] Checking ssh with "ssh -V"
[21:02:56.512] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[21:02:56.516] Running script with connection command: ssh -T -D 58500 cs420 bash
[21:02:56.518] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:02:56.741] > ]0;C:\WINDOWS\System32\cmd.exe
[21:02:56.742] Got some output, clearing connection timeout
[21:02:56.798] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[21:02:56.811] > @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!     
> It is also possible that a host key has just been changed.
> The fingerprint for the ECDSA key sent by the remote host is
> SHA256:Xjhyh19R1BVdjGdT04TFsw8J3sTv8tmw9YfK6BokIeI.
> Please contact your system administrator.
> Add correct host key in C:\\Users\\CHOI/.ssh/known_hosts to get rid of this mess
> age.
> Offending ECDSA key in C:\\Users\\CHOI/.ssh/known_hosts:3
> ECDSA host key for [cp-service.kaist.ac.kr]:13002 has changed and you have reque
> sted strict checking.
> Host key verification failed.
> 프로세스에서 없는 파이프에 쓰려고 했습니다.
> 
[21:02:58.081] "install" terminal command done
[21:02:58.081] Install terminal quit with output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[21:02:58.081] Received install output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[21:02:58.081] Failed to parse remote port from server output
[21:02:58.082] Resolver error: Error: 
	at Function.Create (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:584693)
	at Object.t.tryInstall (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:644486
	at async Object.t.withShowDetailsEvent (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:647831)
	at async Object.t.resolve (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:645565)
	at async c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:722872
[21:02:58.085] ------

How can I connect to the server?

**Comment by minseongg** [comment]
Please remove `C:\Users\CHOI/.ssh/known_hosts` and try again. (https://github.com/kaist-cp/cs420/issues/329#issuecomment-1058888025)

**Comment by chhong39** [comment]
now it keeps asking me password and it doesn't let me pass

**Comment by minseongg** [comment]
Can you try `123454321` as password?

**Comment by chhong39** [comment]
It keeps asking me password even if I try 123454321 continuously and it denies access and kick me

[21:28:09.380] Log Level: 2
[21:28:09.381] remote-ssh@0.76.1
[21:28:09.381] win32 x64
[21:28:09.389] SSH Resolver called for "ssh-remote+cs420", attempt 1
[21:28:09.389] "remote.SSH.useLocalServer": false
[21:28:09.389] "remote.SSH.showLoginTerminal": false
[21:28:09.390] "remote.SSH.remotePlatform": {"cs420":"linux"}
[21:28:09.390] "remote.SSH.path": undefined
[21:28:09.390] "remote.SSH.configFile": undefined
[21:28:09.390] "remote.SSH.useFlock": true
[21:28:09.390] "remote.SSH.lockfilesInTmp": false
[21:28:09.390] "remote.SSH.localServerDownload": auto
[21:28:09.390] "remote.SSH.remoteServerListenOnSocket": false
[21:28:09.390] "remote.SSH.showLoginTerminal": false
[21:28:09.390] "remote.SSH.defaultExtensions": []
[21:28:09.390] "remote.SSH.loglevel": 2
[21:28:09.391] "remote.SSH.enableDynamicForwarding": true
[21:28:09.391] "remote.SSH.enableRemoteCommand": false
[21:28:09.391] "remote.SSH.serverPickPortsFromRange": {}
[21:28:09.391] "remote.SSH.serverInstallPath": {}
[21:28:09.414] SSH Resolver called for host: cs420
[21:28:09.414] Setting up SSH remote "cs420"
[21:28:09.437] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[21:28:09.440] Install and start server if needed
[21:28:09.442] Checking ssh with "ssh -V"
[21:28:09.491] > OpenSSH_for_Windows_8.1p1, LibreSSL 
[21:28:09.492] > 3.0.2

[21:28:09.496] Running script with connection command: ssh -T -D 52714 cs420 bash
[21:28:09.498] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:28:09.725] > ]0;C:\WINDOWS\System32\cmd.exe
[21:28:09.725] Got some output, clearing connection timeout
[21:28:09.801] > s20180799@cp-service.kaist.ac.kr's password: 
[21:28:09.802] Showing password prompt
[21:28:13.952] Got password response
[21:28:13.952] "install" wrote data to terminal: "*********"
[21:28:13.968] > 
[21:28:16.004] > Permission denied, please try again.
[21:28:16.020] > s20180799@cp-service.kaist.ac.kr's password: 
[21:28:16.020] Showing password prompt
[21:28:18.992] Got password response
[21:28:18.992] "install" wrote data to terminal: "*********"
[21:28:19.007] > 
[21:28:21.038] > Permission denied, please try again.
[21:28:21.049] > s20180799@cp-service.kaist.ac.kr's password: 
[21:28:21.049] Showing password prompt
[21:29:29.879] Got password response
[21:29:29.880] "install" wrote data to terminal: "*********"
[21:29:29.894] > 
[21:29:31.927] > s20180799@cp-service.kaist.ac.kr: Permission denied (publickey,password).
[21:29:31.941] > 프로세스에서 없는 파이프에 쓰려고 했습니다.
[21:29:33.247] "install" terminal command done
[21:29:33.247] Install terminal quit with output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[21:29:33.248] Received install output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[21:29:33.248] Failed to parse remote port from server output
[21:29:33.248] Resolver error: Error: 
	at Function.Create (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:584693)
	at Object.t.tryInstall (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:644486
	at async Object.t.withShowDetailsEvent (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:647831)
	at async Object.t.resolve (c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:645565)
	at async c:\Users\CHOI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:722872
[21:29:33.253] ------

**Comment by minseongg** [comment]
Sorry, I don't know the reason.. We'll trying to fix it and let you know. Sorry for the inconvenience.

**Comment by ShinWonho** [comment]
I'm also suffering from the similar issue.

I remove ~/.ssh/known_hosts and try `123454321` as password, but I cannot connect to the server.

<img width="360" alt="스크린샷 2022-03-05 오후 2 07 26" src="https://user-images.githubusercontent.com/50018375/156868909-d8c58da7-5067-4c26-98c0-3740a44aacfc.png">

**Comment by hyn2028** [comment]
I'm in the same situation.

If I try with the password I changed and 123454321 , all logins fail.

Fortunately, I was able to log in using the SSH key that was set in advance.

**Comment by jeehoonkang** [comment]
I wish now all problems are gone. Please try again.

**Comment by jeehoonkang** [comment]
Duplicated with #329
