### ISSUE TITLE
[Question] [HW2] Redeuce Error

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#375]
There seems to be a question about a similar error about hw1, but it doesn't help.

I finished the implementation and tested it with the grader. The test for example passed, but there is a problem in fuzzing as shown below.
```
Fuzzing with 80 test cases.
Test case #0 (skipped: 0)
clang: 157, kecc: 157

Test case #1 (skipped: 0)
clang: 99, kecc: 187
thread 'main' panicked at 'assertion failed: `(left == right)`
...
```
It seems that the my ir for the currently created ```test_policed.c``` is not generated properly, so now I want to run the reducer to check which part is the problem.
```
python3 tests/fuzz.py --print --reduce
```
But the reducer fails as below.
```
Traceback (most recent call last):
  File "tests/fuzz.py", line 334, in <module>
    creduce(tests_dir, fuzz_arg, args.clang_analyze)
  File "tests/fuzz.py", line 238, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy --timing --timeout 20 ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
  0%|                                                                                                                                              | [Elapsed:00:00, <ETA:?]
```

For reference, ```creduce``` seems to have failed with the following message.
```
C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/s20180463/kecc-public/tests/test_reduced.c $DIR
  cd $DIR
  /home/s20180463/kecc-public/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.
```

I was wondering if this test case was the only problem, so I tried changing the seed of the fuzzer, but it fails with the same problem.

**Comment by minseongg** [comment]
Could you try with `python3 tests/fuzz.py --irgen --reduce`?

`--print` option is used for homework 1.

**Comment by hyn2028** [comment]
That's a stupid question... it works. thank you.
