### ISSUE TITLE
[HW2 Fuzzer] Fuzzer fails to reduce at all.

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs420#401]
I have started fuzzing for HW2, and noticed that the fuzzer does not recuse automatically at all, with the following message

```bash
>> python3 tests/fuzz.py --irgen
Use default random seed
Building KECC..
    Finished release [optimized] target(s) in 0.11s
Fuzzing with infinitely many test cases.  Please press [ctrl+C] to break.
Test case #0 (skipped: 0)
Traceback (most recent call last):
  File "tests/fuzz.py", line 335, in <module>
    fuzz(tests_dir, fuzz_arg, args.num, args.easy)
  File "tests/fuzz.py", line 278, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `/home/s20223506/cs420-Homework/target/release/fuzz -i /home/s20223506/cs420-Homework/tests/test_polished.c` failed with exit code 101.
>> python3 tests/fuzz.py --irgen --reduce
  0%|                                                                                                                                                                                                | [Elapsed:00:00, <ETA:?]
Traceback (most recent call last):
  File "tests/fuzz.py", line 333, in <module>
    creduce(tests_dir, fuzz_arg, args.clang_analyze)
  File "tests/fuzz.py", line 238, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy --timing --timeout 20 ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
  0%|         
```

I have cleared all generated files and re-tired, but still failed to reduce. 

`reduce-criteria.sh`
```bash
#!/usr/bin/env bash

rm -f out*.txt

#ulimit -t 3000                                                                                                                                                                                             
#ulimit -v 2000000                                                                                                                                                                                          

if
  (! gcc -Wall -Wextra test_reduced.c > out_gcc.txt 2>&1 ||\
  ! /home/s20223506/cs420-Homework/target/release/kecc --parse test_reduced.c >/dev/null 2>&1)
then
  exit 1
fi

if
  [ -i = '-i' ] &&\
  (! clang -pedantic -Wall -Werror=strict-prototypes -c test_reduced.c > out_clang.txt 2>&1 ||\
  grep 'main-return-type' out_clang.txt ||\
  grep 'conversions than data arguments' out_clang.txt ||\
  grep 'int-conversion' out_clang.txt ||\
  grep 'ordered comparison between pointer and zero' out_clang.txt ||\
  grep 'ordered comparison between pointer and integer' out_clang.txt ||\
  grep 'eliding middle term' out_clang.txt ||\
  grep 'end of non-void function' out_clang.txt ||\
  grep 'invalid in C99' out_clang.txt ||\
  grep 'specifies type' out_clang.txt ||\
  grep 'should return a value' out_clang.txt ||\
  grep 'uninitialized' out_clang.txt ||\
  grep 'incompatible pointer to' out_clang.txt ||\
  grep 'incompatible integer to' out_clang.txt ||\
  grep 'type specifier missing' out_clang.txt ||\
  grep 'implicit-function-declaration' out_clang.txt ||\
  grep 'infinite-recursion' out_clang.txt ||\
  grep 'pointer-bool-conversion' out_clang.txt ||\
  grep 'non-void function does not return a value' out_clang.txt ||\
  grep 'too many arguments in call' out_clang.txt ||\
  grep 'declaration does not declare anything' out_clang.txt ||\
  grep 'not equal to a null pointer is always true' out_clang.txt ||\
  grep 'empty struct is a GNU extension' out_clang.txt ||\
  grep 'uninitialized' out_gcc.txt ||\
  grep 'without a cast' out_gcc.txt ||\
  grep 'control reaches end' out_gcc.txt ||\
  grep 'return type defaults' out_gcc.txt ||\
  grep 'cast from pointer to integer' out_gcc.txt ||\
  grep 'useless type name in empty declaration' out_gcc.txt ||\
  grep 'no semicolon at end' out_gcc.txt ||\
  grep 'type defaults to' out_gcc.txt ||\
  grep 'too few arguments for format' out_gcc.txt ||\
  grep 'incompatible pointer' out_gcc.txt ||\
  grep 'ordered comparison of pointer with integer' out_gcc.txt ||\
  grep 'declaration does not declare anything' out_gcc.txt ||\
  grep 'expects type' out_gcc.txt ||\
  grep 'pointer from integer' out_gcc.txt ||\
  grep 'incompatible implicit' out_gcc.txt ||\
  grep 'excess elements in struct initializer' out_gcc.txt ||\
  grep 'comparison between pointer and integer' out_gcc.txt ||\
  grep 'division by zero' out_gcc.txt)
then
  exit 1
fi

if
  [ -i = '-i' ] &&\
  false &&\
  (! clang --analyze -c test_reduced.c > out_analyzer.txt 2>&1 ||\
  grep 'garbage value' out_analyzer.txt)
then
  exit 1
fi

/home/s20223506/cs420-Homework/target/release/fuzz -i test_reduced.c > out_fuzz.txt 2>&1

if
  [ -i = '-p' ]
then
  grep 'panicked' out_fuzz.txt
else
  grep 'assertion failed' out_fuzz.txt
fi
```
Other generated files are too large to add here, I'll send them to the TA if they want to check it.

**Comment by minseongg** [comment]
Could you follow this comment? https://github.com/kaist-cp/cs420/issues/386#issuecomment-1108909023

**Comment by Lee-Janggun** [comment]
I since hand-reduced and fixed the issue, so I can't do it right now. However, my problem was indeed a panic, so I think the modification will fix my problem. Thank you for the comment!

**Comment by minseongg** [comment]
We fixed it in https://github.com/kaist-cp/kecc-public/commit/2f280650a8776298e555c1081c32c5fdac93ad2d.
