### ISSUE TITLE
[HW1] Getting exception while fuzzing. Exception: Failed to build Csmith (exit code: 127)

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs420#463]
```
running 1 test
[testing "examples/c/cmp.c"]
[testing "examples/c/foo4.c"]
[testing "examples/c/while_continue_break.c"]
[testing "examples/c/simple_if.c"]
[testing "examples/c/fibonacci.c"]
[testing "examples/c/complete_cond.c"]
[testing "examples/c/sizeof.c"]
[testing "examples/c/struct.c"]
[testing "examples/c/struct4.c"]
[testing "examples/c/fib2.c"]
[testing "examples/c/sizeof3.c"]
[testing "examples/c/shift.c"]
[testing "examples/c/typecast.c"]
[testing "examples/c/complement.c"]
[testing "examples/c/array2.c"]
[testing "examples/c/comma.c"]
[testing "examples/c/float.c"]
[testing "examples/c/array3.c"]
[testing "examples/c/gcd.c"]
[testing "examples/c/integer_literal2.c"]
[testing "examples/c/sizeof2.c"]
[testing "examples/c/fib3.c"]
[testing "examples/c/typedef.c"]
[testing "examples/c/for_continue_break.c"]
[testing "examples/c/foo.c"]
[testing "examples/c/pointer.c"]
[testing "examples/c/unary.c"]
[testing "examples/c/logical_op.c"]
[testing "examples/c/foo2.c"]
[testing "examples/c/switch.c"]
[testing "examples/c/bitwise.c"]
[testing "examples/c/minus_constant.c"]
[testing "examples/c/foo3.c"]
[testing "examples/c/simple_cond.c"]
[testing "examples/c/simple.c"]
[testing "examples/c/float2.c"]
[testing "examples/c/bar.c"]
[testing "examples/c/negate.c"]
[testing "examples/c/test.c"]
[testing "examples/c/fib4.c"]
[testing "examples/c/struct2.c"]
[testing "examples/c/simple_for.c"]
[testing "examples/c/array.c"]
[testing "examples/c/temp.c"]
[testing "examples/c/cond.c"]
[testing "examples/c/return_void.c"]
[testing "examples/c/array4.c"]
[testing "examples/c/array5.c"]
[testing "examples/c/temp2.c"]
[testing "examples/c/alignof.c"]
[testing "examples/c/integer_literal.c"]
[testing "examples/c/struct3.c"]
[testing "examples/c/fib5.c"]
[testing "examples/c/cond_and_loop.c"]
test test_examples_write_c ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 11 filtered out; finished in 1.25s

Set seed as 22
Building KECC..
   Compiling kecc v0.1.0 (/home/s20190599/kecc-public)
    Finished release [optimized] target(s) in 7.77s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  622k  100  622k    0     0   316k      0  0:00:01  0:00:01 --:--:--  316k
csmith-2.3.0/
csmith-2.3.0/configure.ac
csmith-2.3.0/scripts/
csmith-2.3.0/scripts/launchn.pl
csmith-2.3.0/scripts/compiler_test.pl
csmith-2.3.0/scripts/Makefile.in
csmith-2.3.0/scripts/CMakeLists.txt
csmith-2.3.0/scripts/compiler_test.in
csmith-2.3.0/scripts/Makefile.am
csmith-2.3.0/runtime/
csmith-2.3.0/runtime/windows/
csmith-2.3.0/runtime/windows/stdint.h
csmith-2.3.0/runtime/safe_abbrev.h
csmith-2.3.0/runtime/stdint_ia64.h
csmith-2.3.0/runtime/platform_generic.h
csmith-2.3.0/runtime/platform_avr.h
csmith-2.3.0/runtime/safe_math_macros_notmp.m4
csmith-2.3.0/runtime/random_inc.h
csmith-2.3.0/runtime/safe_math.m4
csmith-2.3.0/runtime/stdint_msp430.h
csmith-2.3.0/runtime/platform_msp430.h
csmith-2.3.0/runtime/custom_stdint_x86.h
csmith-2.3.0/runtime/csmith.h
csmith-2.3.0/runtime/stdint_ia32.h
csmith-2.3.0/runtime/Makefile.in
csmith-2.3.0/runtime/custom_limits.h
csmith-2.3.0/runtime/CMakeLists.txt
csmith-2.3.0/runtime/safe_math_macros.m4
csmith-2.3.0/runtime/stdint_avr.h
csmith-2.3.0/runtime/volatile_runtime.c
csmith-2.3.0/runtime/volatile_runtime.h
csmith-2.3.0/runtime/csmith_minimal.h
csmith-2.3.0/runtime/Makefile.am
csmith-2.3.0/aclocal.m4
csmith-2.3.0/m4/
csmith-2.3.0/m4/ltoptions.m4
csmith-2.3.0/m4/ltsugar.m4
csmith-2.3.0/m4/libtool.m4
csmith-2.3.0/m4/lt~obsolete.m4
csmith-2.3.0/m4/ltversion.m4
csmith-2.3.0/AUTHORS
csmith-2.3.0/TODO
csmith-2.3.0/version.m4
csmith-2.3.0/autoconf/
csmith-2.3.0/autoconf/install-sh
csmith-2.3.0/autoconf/config.guess
csmith-2.3.0/autoconf/ltmain.sh
csmith-2.3.0/autoconf/config.sub
csmith-2.3.0/autoconf/missing
csmith-2.3.0/autoconf/compile
csmith-2.3.0/autoconf/depcomp
csmith-2.3.0/COPYING
csmith-2.3.0/NEWS
csmith-2.3.0/doc/
csmith-2.3.0/doc/probabilities.txt
csmith-2.3.0/doc/Makefile.in
csmith-2.3.0/doc/CMakeLists.txt
csmith-2.3.0/doc/Makefile.am
csmith-2.3.0/configure
csmith-2.3.0/ChangeLog
csmith-2.3.0/git-hash.sh
csmith-2.3.0/INSTALL
csmith-2.3.0/README
csmith-2.3.0/cmake/
csmith-2.3.0/cmake/GetGitRevisionDescription.cmake.in
csmith-2.3.0/cmake/GetGitRevisionDescription.cmake
csmith-2.3.0/cmake_config.h.in
csmith-2.3.0/Makefile.in
csmith-2.3.0/config.h.in
csmith-2.3.0/CMakeLists.txt
csmith-2.3.0/src/
csmith-2.3.0/src/DefaultOutputMgr.cpp
csmith-2.3.0/src/Error.cpp
csmith-2.3.0/src/StringUtils.cpp
csmith-2.3.0/src/FunctionInvocationBinary.cpp
csmith-2.3.0/src/DeltaMonitor.h
csmith-2.3.0/src/StatementReturn.h
csmith-2.3.0/src/DepthSpec.cpp
csmith-2.3.0/src/Sequence.h
csmith-2.3.0/src/SafeOpFlags.h
csmith-2.3.0/src/Probabilities.h
csmith-2.3.0/src/ExtensionValue.h
csmith-2.3.0/src/SequenceLineParser.h
csmith-2.3.0/src/CrestExtension.h
csmith-2.3.0/src/DFSOutputMgr.h
csmith-2.3.0/src/Function.cpp
csmith-2.3.0/src/CFGEdge.h
csmith-2.3.0/src/ReducerOutputMgr.cpp
csmith-2.3.0/src/Function.h
csmith-2.3.0/src/StatementFor.h
csmith-2.3.0/src/StatementIf.cpp
csmith-2.3.0/src/Reducer.h
csmith-2.3.0/src/SimpleDeltaRndNumGenerator.cpp
csmith-2.3.0/src/SplatExtension.cpp
csmith-2.3.0/src/SequenceFactory.h
csmith-2.3.0/src/Type.cpp
csmith-2.3.0/src/Statement.cpp
csmith-2.3.0/src/Bookkeeper.cpp
csmith-2.3.0/src/CoverageTestExtension.h
csmith-2.3.0/src/rand48/
csmith-2.3.0/src/rand48/rand48.h
csmith-2.3.0/src/rand48/lrand48.c
csmith-2.3.0/src/rand48/_rand48.c
csmith-2.3.0/src/rand48/srand48.c
csmith-2.3.0/src/AbsProgramGenerator.h
csmith-2.3.0/src/platform.cpp
csmith-2.3.0/src/DepthSpec.h
csmith-2.3.0/src/OutputMgr.h
csmith-2.3.0/src/FunctionInvocationUser.cpp
csmith-2.3.0/src/DFSOutputMgr.cpp
csmith-2.3.0/src/AbsRndNumGenerator.cpp
csmith-2.3.0/src/Expression.cpp
csmith-2.3.0/src/DFSRndNumGenerator.h
csmith-2.3.0/src/CompatibleChecker.h
csmith-2.3.0/src/DFSProgramGenerator.cpp
csmith-2.3.0/src/KleeExtension.h
csmith-2.3.0/src/DFSRndNumGenerator.cpp
csmith-2.3.0/src/FactMgr.h
csmith-2.3.0/src/ReducerOutputMgr.h
csmith-2.3.0/src/Expression.h
csmith-2.3.0/src/CommonMacros.h
csmith-2.3.0/src/ExpressionComma.h
csmith-2.3.0/src/FunctionInvocationUnary.h
csmith-2.3.0/src/VectorFilter.cpp
csmith-2.3.0/src/AbsProgramGenerator.cpp
csmith-2.3.0/src/ExpressionVariable.h
csmith-2.3.0/src/Probabilities.cpp
csmith-2.3.0/src/FunctionInvocationUser.h
csmith-2.3.0/src/Error.h
csmith-2.3.0/src/Variable.h
csmith-2.3.0/src/ExpressionVariable.cpp
csmith-2.3.0/src/Finalization.h
csmith-2.3.0/src/SimpleDeltaSequence.cpp
csmith-2.3.0/src/LinearSequence.h
csmith-2.3.0/src/MspFilters.cpp
csmith-2.3.0/src/ExpressionComma.cpp
csmith-2.3.0/src/VariableSelector.cpp
csmith-2.3.0/src/ExtensionMgr.cpp
csmith-2.3.0/src/FactUnion.cpp
csmith-2.3.0/src/CFGEdge.cpp
csmith-2.3.0/src/PartialExpander.cpp
csmith-2.3.0/src/Effect.cpp
csmith-2.3.0/src/StatementIf.h
csmith-2.3.0/src/FactUnion.h
csmith-2.3.0/src/ArrayVariable.h
csmith-2.3.0/src/RandomProgramGenerator.cpp
csmith-2.3.0/src/Sequence.cpp
csmith-2.3.0/src/CVQualifiers.cpp
csmith-2.3.0/src/DefaultRndNumGenerator.cpp
csmith-2.3.0/src/CGOptions.cpp
csmith-2.3.0/src/ExpressionAssign.cpp
csmith-2.3.0/src/DefaultProgramGenerator.h
csmith-2.3.0/src/StatementAssign.cpp
csmith-2.3.0/src/KleeExtension.cpp
csmith-2.3.0/src/ExpressionFuncall.h
csmith-2.3.0/src/StatementExpr.cpp
csmith-2.3.0/src/util.h
csmith-2.3.0/src/random.cpp
csmith-2.3.0/src/FunctionInvocation.cpp
csmith-2.3.0/src/Bookkeeper.h
csmith-2.3.0/src/StatementReturn.cpp
csmith-2.3.0/src/Block.cpp
csmith-2.3.0/src/RandomNumber.cpp
csmith-2.3.0/src/Constant.h
csmith-2.3.0/src/DefaultProgramGenerator.cpp
csmith-2.3.0/src/Common.h
csmith-2.3.0/src/Constant.cpp
csmith-2.3.0/src/FunctionInvocationUnary.cpp
csmith-2.3.0/src/StatementAssign.h
csmith-2.3.0/src/MspFilters.h
csmith-2.3.0/src/Lhs.cpp
csmith-2.3.0/src/StatementContinue.h
csmith-2.3.0/src/Variable.cpp
csmith-2.3.0/src/FactPointTo.cpp
csmith-2.3.0/src/CGContext.h
csmith-2.3.0/src/StatementFor.cpp
csmith-2.3.0/src/FactPointTo.h
csmith-2.3.0/src/CGContext.cpp
csmith-2.3.0/src/Lhs.h
csmith-2.3.0/src/CoverageTestExtension.cpp
csmith-2.3.0/src/StatementGoto.h
csmith-2.3.0/src/StatementArrayOp.cpp
csmith-2.3.0/src/Fact.cpp
csmith-2.3.0/src/Filter.h
csmith-2.3.0/src/random.h
csmith-2.3.0/src/StatementBreak.h
csmith-2.3.0/src/git_version.cpp.in
csmith-2.3.0/src/StatementContinue.cpp
csmith-2.3.0/src/Reducer.cpp
csmith-2.3.0/src/VectorFilter.h
csmith-2.3.0/src/Statement.h
csmith-2.3.0/src/AbsExtension.h
csmith-2.3.0/src/StringUtils.h
csmith-2.3.0/src/Makefile.in
csmith-2.3.0/src/util.cpp
csmith-2.3.0/src/StatementArrayOp.h
csmith-2.3.0/src/StatementExpr.h
csmith-2.3.0/src/RandomNumber.h
csmith-2.3.0/src/Enumerator.h
csmith-2.3.0/src/platform.h
csmith-2.3.0/src/DFSProgramGenerator.h
csmith-2.3.0/src/Finalization.cpp
csmith-2.3.0/src/SplatExtension.h
csmith-2.3.0/src/Effect.h
csmith-2.3.0/src/CMakeLists.txt
csmith-2.3.0/src/FunctionInvocation.h
csmith-2.3.0/src/Filter.cpp
csmith-2.3.0/src/FactMgr.cpp
csmith-2.3.0/src/CrestExtension.cpp
csmith-2.3.0/src/ExtensionValue.cpp
csmith-2.3.0/src/Fact.h
csmith-2.3.0/src/DefaultOutputMgr.h
csmith-2.3.0/src/SafeOpFlags.cpp
csmith-2.3.0/src/PartialExpander.h
csmith-2.3.0/src/git_version.h
csmith-2.3.0/src/Block.h
csmith-2.3.0/src/DefaultRndNumGenerator.h
csmith-2.3.0/src/AbsExtension.cpp
csmith-2.3.0/src/ArrayVariable.cpp
csmith-2.3.0/src/ProbabilityTable.h
csmith-2.3.0/src/CompatibleChecker.cpp
csmith-2.3.0/src/SimpleDeltaSequence.h
csmith-2.3.0/src/ExpressionAssign.h
csmith-2.3.0/src/StatementGoto.cpp
csmith-2.3.0/src/VariableSelector.h
csmith-2.3.0/src/LinearSequence.cpp
csmith-2.3.0/src/OutputMgr.cpp
csmith-2.3.0/src/FunctionInvocationBinary.h
csmith-2.3.0/src/Type.h
csmith-2.3.0/src/DeltaMonitor.cpp
csmith-2.3.0/src/CVQualifiers.h
csmith-2.3.0/src/StatementBreak.cpp
csmith-2.3.0/src/AbsRndNumGenerator.h
csmith-2.3.0/src/ExpressionFuncall.cpp
csmith-2.3.0/src/SimpleDeltaRndNumGenerator.h
csmith-2.3.0/src/SequenceFactory.cpp
csmith-2.3.0/src/Makefile.am
csmith-2.3.0/src/ExtensionMgr.h
csmith-2.3.0/src/CGOptions.h
csmith-2.3.0/Makefile.am
/bin/sh: 1: cmake: not found
Traceback (most recent call last):
  File "/home/s20190599/kecc-public/tests/fuzz.py", line 356, in <module>
    fuzz(tests_dir, fuzz_arg, args.num, args.easy)
  File "/home/s20190599/kecc-public/tests/fuzz.py", line 268, in fuzz
    csmith_bin, csmith_inc = install_csmith(tests_dir)
  File "/home/s20190599/kecc-public/tests/fuzz.py", line 108, in install_csmith
    raise Exception("Failed to build Csmith (exit code: {})".format(proc.returncode))
Exception: Failed to build Csmith (exit code: 127)

```

Above is what I've got from running `./scripts/grade-write_c.sh`.
Same exception occurs when I fuzz manually by `python3 tests/fuzz.py`
What should be the problem?

**Comment by jirheee** [comment]
Hello, are you running kecc in your local machine? If so, we recommend you to use the machine we provided.

**Comment by jirheee** [comment]
Hello, we found out that there are some dependency issues related to running fuzzer on the dev server. It will be fixed ASAP. Sorry for inconvenience. I'll ping on this issue as soon as the problem is fixed.

**Comment by YoonseokJeong** [comment]
Thank you!

**Comment by jirheee** [comment]
@YoonseokJeong We have installed all the dependencies on the server! 🚀
