### ISSUE TITLE
[Question] What should I do to resolve 'Exception: Failed to build Csmith (exit code: 127)'?

### ISSUE THREAD

**Issue by lhi0901** [kaist-cp/cs420#499]
When I run `./scripts/grade-irgen.sh`, the following error occurs.
(same as #463 )

`/bin/sh: 1: cmake: not found
Traceback (most recent call last):
  File "/home/s20190527/kecc-public/tests/fuzz.py", line 356, in <module>
    fuzz(tests_dir, fuzz_arg, args.num, args.easy)
  File "/home/s20190527/kecc-public/tests/fuzz.py", line 268, in fuzz
    csmith_bin, csmith_inc = install_csmith(tests_dir)
  File "/home/s20190527/kecc-public/tests/fuzz.py", line 108, in install_csmith
    raise Exception("Failed to build Csmith (exit code: {})".format(proc.returncode))
Exception: Failed to build Csmith (exit code: 127)`

Is it a problem with the development server? There were no issues before the midterm exam...

**Comment by jirheee** [comment]
We will look at this issue ASAP

**Comment by jirheee** [comment]
We have re-installed all the necessary dependencies required for fuzzing, and checked that it works well in the dev server. Sorry for inconvenience.

**Comment by lhi0901** [comment]
It's resolved now. Thank you.
