### ISSUE TITLE
[Question] When grading HW1&HW2 on the server, 'gzip: stdin: not in gzip format' error occurs

### ISSUE THREAD

**Issue by lhi0901** [kaist-cp/cs420#521]
I encounter an error when I try to execute the commands './scripts/grade-irgen.sh' or './scripts/grade-write_c.sh' on the server.

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/ubuntu/kecc-public/tests/fuzz.py", line 356, in <module>
    fuzz(tests_dir, fuzz_arg, args.num, args.easy)
  File "/home/ubuntu/kecc-public/tests/fuzz.py", line 268, in fuzz
    csmith_bin, csmith_inc = install_csmith(tests_dir)
  File "/home/ubuntu/kecc-public/tests/fuzz.py", line 98, in install_csmith
    raise Exception("Failed to extract Csmith (exit code: {}): `{}`".format(proc.returncode, " ".join(args)))
Exception: Failed to extract Csmith (exit code: 2): `tar xzvf csmith-2.3.0.tar.gz`
``` 

I'm wondering what might be causing this issue.

**Comment by jirheee** [comment]
Did this error occur after swapping to the new dev server?

**Comment by lhi0901** [comment]
> 

Yes

**Comment by jirheee** [comment]
Oh I think it is guess then it might be some dependency issue. Could you run below commands and try again?

```sh
sudo apt update

apt install \
  git man-db locales \
  vim neovim emacs \
  zsh bash-completion tmux \
  build-essential gcc clang make cmake python3 csmith libcsmith-dev creduce \
  gcc-riscv64-linux-gnu g++-riscv64-linux-gnu qemu-user-static \
  graphviz curl \
  zip python3-pip

pip install tqdm
```

**Comment by lhi0901** [comment]
@jirheee Oh, it is resolved. Thank you!
